// Shared card fixtures for FE and BE tests.
// Shape covers both user cards and scraped catalog cards.
// Note: keep values aligned with frontend `constants.js` and backend Prisma models.

export const CARD_FIXTURES = [
  {
    id: 'card-01',
    cardName: 'AMEX Aeroplan Reserve',
    type: 'AMEX',
    status: 'Open',
    pointsType: 'Aeroplan',
    bank: 'AMEX',
    lineOfCredit: 15000,
    openDate: '2024-01-15',
    closeDate: null,
    possibleReopenDate: null,
    annualCost: 599,
    progression: 80,
    expenses: 5000,
    deadline: '2024-04-15',
    pointsValue: 1200,
    pointsDetails: 'Welcome bonus + everyday spend',
    milesopediaUrl: 'https://milesopedia.com/cartes-de-credit/amex-aeroplan-reserve',
    milesopediaSlug: 'amex-aeroplan-reserve',
    welcomeValueY1: 1200,
    welcomeValueY2: 300,
    noWelcomeBonus: false,
    minSpend: 6000,
    minSpendNotes: 'Within the first 3 months',
    bonusDetails: 'Tiered Aeroplan bonus up to 120,000 pts',
    createdAt: '2024-01-10T10:00:00.000Z',
    updatedAt: '2024-02-01T12:00:00.000Z',
    lastSnapshot: {
      weekStartDate: '2024-02-05',
      pointsValue: 150000,
      expenses: 5200,
    },
  },
  {
    id: 'card-02',
    cardName: 'RBC Avion Visa Infinite',
    type: 'VISA',
    status: 'To_Open',
    pointsType: 'RBC',
    bank: 'RBC',
    lineOfCredit: null,
    openDate: null,
    closeDate: null,
    possibleReopenDate: null,
    annualCost: 120,
    progression: null,
    expenses: null,
    deadline: null,
    pointsValue: null,
    pointsDetails: null,
    milesopediaUrl: 'https://milesopedia.com/cartes-de-credit/rbc-avion-visa-infinite',
    milesopediaSlug: 'rbc-avion-visa-infinite',
    welcomeValueY1: 700,
    welcomeValueY2: 0,
    noWelcomeBonus: false,
    minSpend: 5000,
    minSpendNotes: null,
    bonusDetails: 'Avion welcome bonus with travel redemption',
    createdAt: '2024-01-20T08:00:00.000Z',
    updatedAt: '2024-01-20T08:00:00.000Z',
    lastSnapshot: null,
  },
  {
    id: 'card-03',
    cardName: 'CIBC Aventura Visa Infinite',
    type: 'VISA',
    status: 'Open',
    pointsType: 'CIBC',
    bank: 'CIBC',
    lineOfCredit: 10000,
    openDate: '2023-11-01',
    closeDate: null,
    possibleReopenDate: null,
    annualCost: 139,
    progression: 45,
    expenses: 3000,
    deadline: '2024-02-01',
    pointsValue: 800,
    pointsDetails: 'Aventura welcome with gas & grocery accelerator',
    milesopediaUrl: 'https://milesopedia.com/cartes-de-credit/cibc-aventura-visa-infinite',
    milesopediaSlug: 'cibc-aventura-visa-infinite',
    welcomeValueY1: 800,
    welcomeValueY2: 200,
    noWelcomeBonus: false,
    minSpend: 4000,
    minSpendNotes: 'Grocery and gas count fully',
    bonusDetails: 'Multiple Aventura bonus tiers',
    createdAt: '2023-10-20T10:00:00.000Z',
    updatedAt: '2024-01-05T09:15:00.000Z',
    lastSnapshot: {
      weekStartDate: '2024-01-29',
      pointsValue: 90000,
      expenses: 3100,
    },
  },
  {
    id: 'card-04',
    cardName: 'BMO CashBack World Elite Mastercard',
    type: 'MASTERCARD',
    status: 'Closed',
    pointsType: 'Cashback',
    bank: 'BMO',
    lineOfCredit: 8000,
    openDate: '2022-03-10',
    closeDate: '2023-03-15',
    possibleReopenDate: '2024-03-15',
    annualCost: 120,
    progression: 100,
    expenses: 15000,
    deadline: null,
    pointsValue: 300,
    pointsDetails: '5% cashback intro, then 1–3%',
    milesopediaUrl: null,
    milesopediaSlug: null,
    welcomeValueY1: 300,
    welcomeValueY2: 0,
    noWelcomeBonus: false,
    minSpend: 2000,
    minSpendNotes: null,
    bonusDetails: 'High intro cash back on groceries',
    createdAt: '2022-02-20T10:00:00.000Z',
    updatedAt: '2023-03-20T10:00:00.000Z',
    lastSnapshot: null,
  },
  {
    id: 'card-05',
    cardName: 'Scotiabank Passport Visa Infinite',
    type: 'VISA',
    status: 'Open',
    pointsType: 'Scene',
    bank: 'Scotia',
    lineOfCredit: 12000,
    openDate: '2023-06-01',
    closeDate: null,
    possibleReopenDate: null,
    annualCost: 150,
    progression: 60,
    expenses: 4500,
    deadline: '2023-09-01',
    pointsValue: 500,
    pointsDetails: 'No FX fees + Scene+ points',
    milesopediaUrl: 'https://milesopedia.com/cartes-de-credit/scotia-passport-visa-infinite',
    milesopediaSlug: 'scotia-passport-visa-infinite',
    welcomeValueY1: 500,
    welcomeValueY2: 100,
    noWelcomeBonus: false,
    minSpend: 3000,
    minSpendNotes: 'Within first 90 days',
    bonusDetails: 'Scene+ bonus with no FX',
    createdAt: '2023-05-20T09:00:00.000Z',
    updatedAt: '2023-08-15T11:30:00.000Z',
    lastSnapshot: {
      weekStartDate: '2023-08-07',
      pointsValue: 60000,
      expenses: 4700,
    },
  },
  {
    id: 'card-06',
    cardName: 'TD First Class Travel Visa Infinite',
    type: 'VISA',
    status: 'Refused',
    pointsType: 'TD',
    bank: 'TD',
    lineOfCredit: null,
    openDate: null,
    closeDate: null,
    possibleReopenDate: null,
    annualCost: 139,
    progression: null,
    expenses: null,
    deadline: null,
    pointsValue: null,
    pointsDetails: null,
    milesopediaUrl: 'https://milesopedia.com/cartes-de-credit/td-first-class-travel-visa-infinite',
    milesopediaSlug: 'td-first-class-travel-visa-infinite',
    welcomeValueY1: 600,
    welcomeValueY2: 100,
    noWelcomeBonus: false,
    minSpend: 1000,
    minSpendNotes: null,
    bonusDetails: 'TD Rewards travel statement credit',
    createdAt: '2024-01-05T08:30:00.000Z',
    updatedAt: '2024-01-10T08:30:00.000Z',
    lastSnapshot: null,
  },
  {
    id: 'card-07',
    cardName: 'BNC World Elite Mastercard',
    type: 'MASTERCARD',
    status: 'Open',
    pointsType: 'BNC',
    bank: 'BNC',
    lineOfCredit: 9000,
    openDate: '2023-01-10',
    closeDate: null,
    possibleReopenDate: null,
    annualCost: 150,
    progression: 30,
    expenses: 2000,
    deadline: '2023-04-10',
    pointsValue: 400,
    pointsDetails: 'BNC Récompenses points',
    milesopediaUrl: 'https://milesopedia.com/cartes-de-credit/bnc-world-elite-mastercard',
    milesopediaSlug: 'bnc-world-elite-mastercard',
    welcomeValueY1: 400,
    welcomeValueY2: 0,
    noWelcomeBonus: false,
    minSpend: 2500,
    minSpendNotes: null,
    bonusDetails: 'Bonus on groceries and gas',
    createdAt: '2022-12-20T10:00:00.000Z',
    updatedAt: '2023-02-15T10:00:00.000Z',
    lastSnapshot: {
      weekStartDate: '2023-03-06',
      pointsValue: 45000,
      expenses: 2100,
    },
  },
  {
    id: 'card-08',
    cardName: 'Marriott Bonvoy American Express',
    type: 'AMEX',
    status: 'Closed',
    pointsType: 'Marriott_Bonvoy',
    bank: 'AMEX',
    lineOfCredit: 7000,
    openDate: '2021-05-01',
    closeDate: '2023-05-01',
    possibleReopenDate: '2025-05-01',
    annualCost: 120,
    progression: 100,
    expenses: 6000,
    deadline: '2021-08-01',
    pointsValue: 600,
    pointsDetails: 'Marriott Bonvoy free night + points',
    milesopediaUrl: 'https://milesopedia.com/cartes-de-credit/marriott-bonvoy-amex',
    milesopediaSlug: 'marriott-bonvoy-amex',
    welcomeValueY1: 600,
    welcomeValueY2: 300,
    noWelcomeBonus: false,
    minSpend: 3000,
    minSpendNotes: null,
    bonusDetails: 'Free night certificate after anniversary',
    createdAt: '2021-04-20T10:00:00.000Z',
    updatedAt: '2023-04-25T10:00:00.000Z',
    lastSnapshot: null,
  },
  {
    id: 'card-09',
    cardName: 'Brim Cashback Mastercard',
    type: 'MASTERCARD',
    status: 'Open',
    pointsType: 'Cashback',
    bank: 'BMO',
    lineOfCredit: 5000,
    openDate: '2022-09-01',
    closeDate: null,
    possibleReopenDate: null,
    annualCost: 0,
    progression: 20,
    expenses: 1500,
    deadline: null,
    pointsValue: 150,
    pointsDetails: 'No FX, no annual fee, cash back',
    milesopediaUrl: null,
    milesopediaSlug: null,
    welcomeValueY1: 150,
    welcomeValueY2: 0,
    noWelcomeBonus: false,
    minSpend: null,
    minSpendNotes: null,
    bonusDetails: null,
    createdAt: '2022-08-20T09:00:00.000Z',
    updatedAt: '2022-10-01T09:00:00.000Z',
    lastSnapshot: null,
  },
  {
    id: 'card-10',
    cardName: 'Scotiabank Gold American Express',
    type: 'AMEX',
    status: 'To_Open',
    pointsType: 'Scene',
    bank: 'Scotia',
    lineOfCredit: null,
    openDate: null,
    closeDate: null,
    possibleReopenDate: null,
    annualCost: 120,
    progression: null,
    expenses: null,
    deadline: null,
    pointsValue: null,
    pointsDetails: null,
    milesopediaUrl: 'https://milesopedia.com/cartes-de-credit/scotia-gold-amex',
    milesopediaSlug: 'scotia-gold-amex',
    welcomeValueY1: 650,
    welcomeValueY2: 150,
    noWelcomeBonus: false,
    minSpend: 1000,
    minSpendNotes: 'Grocery and dining spend',
    bonusDetails: 'High multiplier on dining and groceries',
    createdAt: '2024-01-01T10:00:00.000Z',
    updatedAt: '2024-01-01T10:00:00.000Z',
    lastSnapshot: null,
  },
  {
    id: 'card-11',
    cardName: 'TD Aeroplan Visa Infinite',
    type: 'VISA',
    status: 'Open',
    pointsType: 'Aeroplan',
    bank: 'TD',
    lineOfCredit: 10000,
    openDate: '2023-09-01',
    closeDate: null,
    possibleReopenDate: null,
    annualCost: 139,
    progression: 70,
    expenses: 3500,
    deadline: '2023-12-01',
    pointsValue: 900,
    pointsDetails: 'TD Aeroplan bonus with free first bag',
    milesopediaUrl: 'https://milesopedia.com/cartes-de-credit/td-aeroplan-visa-infinite',
    milesopediaSlug: 'td-aeroplan-visa-infinite',
    welcomeValueY1: 900,
    welcomeValueY2: 200,
    noWelcomeBonus: false,
    minSpend: 1500,
    minSpendNotes: 'Within 90 days',
    bonusDetails: 'Multiple Aeroplan tiers',
    createdAt: '2023-08-15T10:00:00.000Z',
    updatedAt: '2023-11-15T10:00:00.000Z',
    lastSnapshot: {
      weekStartDate: '2023-11-13',
      pointsValue: 110000,
      expenses: 3600,
    },
  },
  {
    id: 'card-12',
    cardName: 'American Express Cobalt',
    type: 'AMEX',
    status: 'Open',
    pointsType: 'Aeroplan',
    bank: 'AMEX',
    lineOfCredit: 3000,
    openDate: '2020-01-01',
    closeDate: null,
    possibleReopenDate: null,
    annualCost: 155,
    progression: 100,
    expenses: 10000,
    deadline: null,
    pointsValue: 500,
    pointsDetails: 'Monthly-point style welcome bonus',
    milesopediaUrl: 'https://milesopedia.com/cartes-de-credit/amex-cobalt',
    milesopediaSlug: 'amex-cobalt',
    welcomeValueY1: 500,
    welcomeValueY2: 500,
    noWelcomeBonus: false,
    minSpend: 500,
    minSpendNotes: 'Monthly minimum spend for bonus',
    bonusDetails: '5x on dining, groceries',
    createdAt: '2019-12-20T10:00:00.000Z',
    updatedAt: '2023-12-20T10:00:00.000Z',
    lastSnapshot: null,
  },
  {
    id: 'card-13',
    cardName: 'VIP Porter World Elite Mastercard',
    type: 'MASTERCARD',
    status: 'To_Open',
    pointsType: 'VIP_Porter',
    bank: 'BMO',
    lineOfCredit: null,
    openDate: null,
    closeDate: null,
    possibleReopenDate: null,
    annualCost: 150,
    progression: null,
    expenses: null,
    deadline: null,
    pointsValue: null,
    pointsDetails: null,
    milesopediaUrl: 'https://milesopedia.com/cartes-de-credit/vip-porter-world-elite',
    milesopediaSlug: 'vip-porter-world-elite',
    welcomeValueY1: 400,
    welcomeValueY2: 0,
    noWelcomeBonus: false,
    minSpend: 2000,
    minSpendNotes: null,
    bonusDetails: 'VIP Porter points for flights',
    createdAt: '2024-02-01T10:00:00.000Z',
    updatedAt: '2024-02-01T10:00:00.000Z',
    lastSnapshot: null,
  },
  {
    id: 'card-14',
    cardName: 'No-Fee Cashback Visa',
    type: 'VISA',
    status: 'Open',
    pointsType: 'Cashback',
    bank: 'CIBC',
    lineOfCredit: 4000,
    openDate: '2021-02-01',
    closeDate: null,
    possibleReopenDate: null,
    annualCost: 0,
    progression: 10,
    expenses: 800,
    deadline: null,
    pointsValue: 50,
    pointsDetails: 'Flat cashback, no welcome bonus',
    milesopediaUrl: null,
    milesopediaSlug: null,
    welcomeValueY1: 0,
    welcomeValueY2: 0,
    noWelcomeBonus: true,
    minSpend: null,
    minSpendNotes: null,
    bonusDetails: 'Card has no welcome offer',
    createdAt: '2021-01-15T10:00:00.000Z',
    updatedAt: '2021-06-15T10:00:00.000Z',
    lastSnapshot: null,
  },
  {
    id: 'card-15',
    cardName: 'Student Cashback Mastercard',
    type: 'MASTERCARD',
    status: 'Open',
    pointsType: 'Cashback',
    bank: 'BNC',
    lineOfCredit: 1000,
    openDate: '2022-09-01',
    closeDate: null,
    possibleReopenDate: null,
    annualCost: 0,
    progression: 40,
    expenses: 2000,
    deadline: null,
    pointsValue: 80,
    pointsDetails: 'Student friendly cashback',
    milesopediaUrl: null,
    milesopediaSlug: null,
    welcomeValueY1: 80,
    welcomeValueY2: 0,
    noWelcomeBonus: false,
    minSpend: 500,
    minSpendNotes: 'Intro bonus on first purchases',
    bonusDetails: null,
    createdAt: '2022-08-20T10:00:00.000Z',
    updatedAt: '2022-12-20T10:00:00.000Z',
    lastSnapshot: null,
  },
  {
    id: 'card-16',
    cardName: 'Premium Travel Visa',
    type: 'VISA',
    status: 'Closed',
    pointsType: 'Aeroplan',
    bank: 'RBC',
    lineOfCredit: 20000,
    openDate: '2019-01-01',
    closeDate: '2021-01-01',
    possibleReopenDate: '2023-01-01',
    annualCost: 399,
    progression: 100,
    expenses: 20000,
    deadline: '2019-04-01',
    pointsValue: 1500,
    pointsDetails: 'High annual fee, huge welcome bonus',
    milesopediaUrl: null,
    milesopediaSlug: null,
    welcomeValueY1: 1500,
    welcomeValueY2: 500,
    noWelcomeBonus: false,
    minSpend: 8000,
    minSpendNotes: null,
    bonusDetails: 'Includes lounge access and insurance',
    createdAt: '2018-12-20T10:00:00.000Z',
    updatedAt: '2020-12-20T10:00:00.000Z',
    lastSnapshot: null,
  },
  {
    id: 'card-17',
    cardName: 'Basic Visa No Rewards',
    type: 'VISA',
    status: 'Open',
    pointsType: 'Cashback',
    bank: 'TD',
    lineOfCredit: 2000,
    openDate: '2018-01-01',
    closeDate: null,
    possibleReopenDate: null,
    annualCost: 0,
    progression: 0,
    expenses: 200,
    deadline: null,
    pointsValue: 0,
    pointsDetails: 'Card used only for credit history',
    milesopediaUrl: null,
    milesopediaSlug: null,
    welcomeValueY1: null,
    welcomeValueY2: null,
    noWelcomeBonus: true,
    minSpend: null,
    minSpendNotes: null,
    bonusDetails: null,
    createdAt: '2017-12-20T10:00:00.000Z',
    updatedAt: '2018-06-20T10:00:00.000Z',
    lastSnapshot: null,
  },
  {
    id: 'card-18',
    cardName: 'Scotia Momentum Cashback Visa',
    type: 'VISA',
    status: 'Open',
    pointsType: 'Cashback',
    bank: 'Scotia',
    lineOfCredit: 7000,
    openDate: '2020-03-01',
    closeDate: null,
    possibleReopenDate: null,
    annualCost: 99,
    progression: 55,
    expenses: 5000,
    deadline: '2020-06-01',
    pointsValue: 250,
    pointsDetails: 'Groceries and recurring payments cashback',
    milesopediaUrl: null,
    milesopediaSlug: null,
    welcomeValueY1: 250,
    welcomeValueY2: 0,
    noWelcomeBonus: false,
    minSpend: 1000,
    minSpendNotes: null,
    bonusDetails: null,
    createdAt: '2020-02-20T10:00:00.000Z',
    updatedAt: '2020-06-20T10:00:00.000Z',
    lastSnapshot: null,
  },
  {
    id: 'card-19',
    cardName: 'Aeroplan Business Amex',
    type: 'AMEX',
    status: 'To_Open',
    pointsType: 'Aeroplan',
    bank: 'AMEX',
    lineOfCredit: null,
    openDate: null,
    closeDate: null,
    possibleReopenDate: null,
    annualCost: 599,
    progression: null,
    expenses: null,
    deadline: null,
    pointsValue: null,
    pointsDetails: null,
    milesopediaUrl: 'https://milesopedia.com/cartes-de-credit/aeroplan-business-amex',
    milesopediaSlug: 'aeroplan-business-amex',
    welcomeValueY1: 1800,
    welcomeValueY2: 300,
    noWelcomeBonus: false,
    minSpend: 15000,
    minSpendNotes: 'Business spending required',
    bonusDetails: 'Business welcome bonus with accelerated multipliers',
    createdAt: '2024-02-05T10:00:00.000Z',
    updatedAt: '2024-02-05T10:00:00.000Z',
    lastSnapshot: null,
  },
  {
    id: 'card-20',
    cardName: 'Entry-Level Student Visa',
    type: 'VISA',
    status: 'Refused',
    pointsType: 'Cashback',
    bank: 'RBC',
    lineOfCredit: null,
    openDate: null,
    closeDate: null,
    possibleReopenDate: null,
    annualCost: 0,
    progression: null,
    expenses: null,
    deadline: null,
    pointsValue: null,
    pointsDetails: null,
    milesopediaUrl: null,
    milesopediaSlug: null,
    welcomeValueY1: null,
    welcomeValueY2: null,
    noWelcomeBonus: true,
    minSpend: null,
    minSpendNotes: 'Application refused',
    bonusDetails: null,
    createdAt: '2024-01-10T10:00:00.000Z',
    updatedAt: '2024-01-15T10:00:00.000Z',
    lastSnapshot: null,
  },
];

